### ISSUE TITLE
Explain development plan

### ISSUE THREAD

**Issue by maxpatiiuk** [maxpatiiuk/eecs-448-pixelland#42]
#### Deployment plan (500-700 words - 5%)
- [x] What are the steps required to deploy your project? (it is already briefly described here: https://github.com/maxpatiiuk/eecs-448-pixelland/blob/main/documentation/README.md#production)
- [x] Who is the potential market?
- [x] What will it cost to deploy it?

Example costs:
  - app store costs
  - costs to get your game on XBoxLive
  -  costs to print disks for distribution
  -  costs to buy domains
  - costs to attend conventions and conference and set up booths

**Comment by nathanrdodson** [comment]
Bulk description is finished; I should add more granularity/specific numbers to the cost section.

https://github.com/maxpatiiuk/eecs-448-pixelland/commit/21ecaf9f17ef2435d5c3687533a1305b2cf2b21a

**Comment by nathanrdodson** [comment]
Finished in https://github.com/maxpatiiuk/eecs-448-pixelland/commit/42a6f530fad512ff262eafc253ee8db42eff2361
