### ISSUE TITLE
Undertake a code review

### ISSUE THREAD

**Issue by maxpatiiuk** [maxpatiiuk/eecs-448-pixelland#44]
#### Code Review (500-700 words – 5%)
- Undertake, as part of a team activity, an inspection of a medium-size code segment using either a Walkthrough or Inspection as described in the lecture on Software Verification

Document the following:
- [ ] List of faults detected
- [ ] Description of each fault
- [ ] Who was assigned to fix each fault
- [ ] How the fault was fixed

**Comment by maxpatiiuk** [comment]
Begun doing a code review as a team.
Went through each view, component, libriary and discussed the game loop.
Found the following issues: https://github.com/maxpatiiuk/eecs-448-pixelland/issues/46, https://github.com/maxpatiiuk/eecs-448-pixelland/issues/47, https://github.com/maxpatiiuk/eecs-448-pixelland/issues/50, and https://github.com/maxpatiiuk/eecs-448-pixelland/issues/51

**Comment by maxxxxxdlp** [comment]
Fixed by @nathanrdodson in 1586f80476654ffb0acb56fc33cde567f5cafb86
Thanks!
